from django.urls import path
 
from .views import *

urlpatterns = [
 
    path('customers/', CustomerListCreateAPIView.as_view(), name='customer-list-create'),  
    path('customers/<int:pk>/', CustomerRetrieveUpdateDestroyAPIView.as_view(), name='customer-detail'),  
    path('customers/parent_acc/', CustomerListView.as_view(), name='customer-list-create-parent'),
    path('supplier/', SupplierListCreateAPIView.as_view(), name='customer-list-create'),  
    path('supplier/<int:pk>/',SupplierRetrieveUpdateDestroyAPIView.as_view(), name='customer-detail'),  
    path('agents/', AgentListCreateAPIView.as_view(), name='customer-list-create'),  
    path('agents/<int:pk>/',AgentRetrieveUpdateDestroyAPIView.as_view(), name='customer-detail'),  
    path('airline/', AirlineListCreateAPIView.as_view(), name='customer-list-create'),  
    path('airline/<int:pk>/',AirlineRetrieveUpdateDestroyAPIView.as_view(), name='customer-detail'),  
    path('users/', UserManagementListCreateAPIView.as_view(), name='customer-list-create'),  
    path('users/<int:pk>/',UserManagementRetrieveUpdateDestroyAPIView.as_view(), name='customer-detail'),  
    path('service/', ServiceListCreateAPIView.as_view(), name='customer-list-create'),  
    path('service/<int:pk>/',ServiceRetrieveUpdateDestroyAPIView.as_view(), name='customer-detail'),  
    path('important-dates/', ImportantDatesListCreateAPIView.as_view(), name='customer-list-create'),  
    path('important-dates/<int:pk>/',ImportantDatesRetrieveUpdateDestroyAPIView.as_view(), name='customer-detail'),  
    path("important-dates/<int:pk>/change-status/", ChangeStatusAPIView.as_view(), name="change-status"),
    path('filter-important-dates/', ImportantDatesFilterAPIView.as_view(), name='filter_important_dates'),
    path('assets/', AssetsListCreateAPIView.as_view(), name='customer-list-create'),  
    path('assets/<int:pk>/',AssetsRetrieveUpdateDestroyAPIView.as_view(), name='customer-detail'), 
    path('expenses/', ExpensesListCreateAPIView.as_view(), name='customer-list-create'),  
    path('expenses/<int:pk>/',ExpensesRetrieveUpdateDestroyAPIView.as_view(), name='customer-detail'),
    path('income/', IncomeListCreateAPIView.as_view(), name='customer-list-create'),  
    path('income/<int:pk>/',IncomeRetrieveUpdateDestroyAPIView.as_view(), name='customer-detail'),
    path('liability/', LiabilityListCreateAPIView.as_view(), name='customer-list-create'),  
    path('liability/<int:pk>/',LiabilityRetrieveUpdateDestroyAPIView.as_view(), name='customer-detail'),
    path('assets-title/', GroupAssetsByTitleAPIView.as_view(), name='assets-list-create'),
    path('group-expenses/', GroupExpensesByTitleAPIView.as_view(), name='group_expenses_by_title'),
    path('group-income/', GroupIncomeByTitleAPIView.as_view(), name='group_income_by_title'),
    path('group-liability/', GroupLiabilityByTitleAPIView.as_view(), name='group_liability_by_title'),
    path('gloabal-assets/', GlobalAssetsListCreateAPIView.as_view(), name='customer-list-create'),  
    path('gloabal-assets/<int:pk>/',GlobalAssetsRetrieveUpdateDestroyAPIView.as_view(), name='customer-detail'),
    path('group-global-assets/', GroupGlobalAssetsByTitleAPIView.as_view(), name='group_global_assets_by_title'),
    path('gloabal-agents/', GlobalAgentsListCreateAPIView.as_view(), name='customer-list-create'),  
    path('gloabal-agents/<int:pk>/',GlobalAgentsRetrieveUpdateDestroyAPIView.as_view(), name='customer-detail'),
    path('group-global-agents/', GroupGlobalAgentByTitleAPIView.as_view(), name='group_global_assets_by_title'),
    path('gloabal-airline/', GlobalAirlineListCreateAPIView.as_view(), name='customer-list-create'),  
    path('gloabal-airline/<int:pk>/',GlobalAirlineRetrieveUpdateDestroyAPIView.as_view(), name='customer-detail'),
    path('group-gloabal-airline/', GroupGlobalAirlineByTitleAPIView.as_view(), name='group_global_assets_by_title'),
    path('gloabal-customer/', GlobalCustomerListCreateAPIView.as_view(), name='customer-list-create'),  
    path('gloabal-customer/<int:pk>/',GlobalCustomerRetrieveUpdateDestroyAPIView.as_view(), name='customer-detail'),
    path('group-gloabal-customer/', GroupGlobalCustomerByTitleAPIView.as_view(), name='group_global_assets_by_title'),
    path('gloabal-expense/', GlobalExpenseListCreateAPIView.as_view(), name='customer-list-create'),  
    path('gloabal-expense/<int:pk>/',GlobalExpenseRetrieveUpdateDestroyAPIView.as_view(), name='customer-detail'),
    path('group-gloabal-expense/', GroupGlobalExpenseByTitleAPIView.as_view(), name='group_global_assets_by_title'),
    path('gloabal-income/', GlobalIncomeListCreateAPIView.as_view(), name='customer-list-create'),  
    path('gloabal-income/<int:pk>/',GlobalIncomeRetrieveUpdateDestroyAPIView.as_view(), name='customer-detail'),
    path('group-gloabal-income/', GroupGlobalIncomeByTitleAPIView.as_view(), name='group_global_assets_by_title'),
    path('gloabal-liability/', GlobalLiabilityListCreateAPIView.as_view(), name='customer-list-create'),  
    path('gloabal-liability/<int:pk>/',GlobalLiabilityRetrieveUpdateDestroyAPIView.as_view(), name='customer-detail'),
    path('group-gloabal-liability/', GroupGlobalLiabilityByTitleAPIView.as_view(), name='group_global_assets_by_title'),
    path('gloabal-neutral/', GlobalNeutralListCreateAPIView.as_view(), name='customer-list-create'),  
    path('gloabal-neutral/<int:pk>/',GlobalNeutralRetrieveUpdateDestroyAPIView.as_view(), name='customer-detail'),
    path('group-gloabal-neutral/', GroupGlobalNeutralByTitleAPIView.as_view(), name='group_global_assets_by_title'),
    path('gloabal-supplier/', GlobalSuppliersListCreateAPIView.as_view(), name='customer-list-create'),  
    path('gloabal-supplier/<int:pk>/',GlobalSuppliersRetrieveUpdateDestroyAPIView.as_view(), name='customer-detail'),
    path('group-gloabal-supplier/', GroupGlobalSuppliersByTitleAPIView.as_view(), name='group_global_assets_by_title'),
    path('neutral/', NeutralListCreateAPIView.as_view(), name='customer-list-create'),  
    path('neutral/<int:pk>/', NeutralRetrieveUpdateDestroyAPIView.as_view(), name='customer-detail'),  
    path('neutral/parent_acc/', NeutralListView.as_view(), name='customer-list-create-parent'),
] 
 
