# Generated by Django 5.1.5 on 2025-02-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('create_child_acc', models.BooleanField(default=True)),
                ('create_parent_acc', models.BooleanField(default=True)),
                ('choose_parent', models.CharField(default=True, max_length=255, null=True)),
                ('op_balance', models.IntegerField(default=True, null=True)),
                ('cr_or_dr', models.CharField(choices=[('CR', 'CR'), ('DR', 'DR')], max_length=20)),
                ('has_credit_limit', models.BooleanField(default=True)),
                ('enter_limit', models.IntegerField(default=True, null=True)),
                ('contact_details', models.TextField(default=True, null=True)),
                ('gst_in', models.CharField(default=True, max_length=255, null=True)),
                ('email', models.EmailField(default=True, max_length=254, null=True, unique=True)),
                ('staff_or_group', models.CharField(default=True, max_length=255, null=True)),
                ('unique_code', models.CharField(unique=True)),
                ('id_or_pan', models.CharField(default=True, max_length=255, null=True)),
                ('notes', models.TextField(default=True, null=True)),
                ('acl_type', models.CharField(choices=[('BC', 'BC'), ('BB', 'BB')], max_length=20)),
            ],
        ),
    ]
