# Generated by Django 5.1.5 on 2025-02-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='unique_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
    ]
