# Generated by Django 5.1.5 on 2025-02-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_alter_customer_choose_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='acl_type',
            field=models.CharField(blank=True, choices=[('BC', 'BC'), ('BB', 'BB')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cr_or_dr',
            field=models.CharField(blank=True, choices=[('CR', 'CR'), ('DR', 'DR')], max_length=20, null=True),
        ),
    ]
