# Generated by Django 5.1.5 on 2025-02-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_importantdates'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantdates',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=20),
        ),
    ]
