# Generated by Django 5.1.5 on 2025-02-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_importantdates_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_head', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, choices=[('Cash And Bank Balance', 'Cash And Bank Balance'), ('Current assets', 'Current assets'), ('Deposite', 'Deposite'), ('Fixed assets', 'Fixed assets'), ('Investment', 'Investment'), ('Loan And Advances', 'Loan And Advances'), ('Staff Advances', 'Staff Advances'), ('Other assets', 'Other assets'), ('Branches', 'Branches'), ('Sundry Debtors', 'Sundry Debtors')], max_length=100, null=True)),
                ('acc_type', models.CharField(blank=True, choices=[('Bank', 'Bank')], max_length=20, null=True)),
                ('op_balance', models.IntegerField(blank=True, null=True)),
                ('cr_or_dr', models.CharField(blank=True, choices=[('CR', 'CR'), ('DR', 'DR')], max_length=20, null=True)),
                ('acc_number', models.CharField(blank=True, max_length=255, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('unique_code', models.CharField(editable=False, max_length=255, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
