# Generated by Django 5.1.5 on 2025-02-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='unique_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='unique_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
