# Generated by Django 5.1.5 on 2025-02-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_assets_unique_id_alter_assets_unique_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_head', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, choices=[('Direct Expenses', 'Direct Expenses'), ('Indirect Expenses', 'Indirect Expenses')], max_length=100, null=True)),
                ('op_balance', models.IntegerField(blank=True, null=True)),
                ('cr_or_dr', models.CharField(blank=True, choices=[('CR', 'CR'), ('DR', 'DR')], max_length=20, null=True)),
                ('has_child_acc', models.BooleanField(default=False)),
                ('unique_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('unique_id', models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True)),
            ],
        ),
    ]
