# Generated by Django 5.1.5 on 2025-02-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_expenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_head', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, choices=[('Visa Service Incomes', 'Visa Service Incomes'), ('Ticketing Incomes', 'Ticketing Incomes'), ('Attestation Incomes', 'Attestation Incomes'), ('Emigration Income', 'Emigration Income'), ('Umrah Income', 'Umrah Income'), ('Other Incomes', 'Other Incomes'), ('Recruitment Incomes', 'Recruitment Incomes'), ('Insurance Incomes', 'Insurance Incomes'), ('Service Income', 'Service Income')], max_length=100, null=True)),
                ('op_balance', models.IntegerField(blank=True, null=True)),
                ('cr_or_dr', models.CharField(blank=True, choices=[('CR', 'CR'), ('DR', 'DR')], max_length=20, null=True)),
                ('has_child_acc', models.BooleanField(default=False)),
                ('unique_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('unique_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='expenses',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
