# Generated by Django 5.1.5 on 2025-02-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_income_alter_expenses_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_head', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, choices=[('Capital Account', 'Capital Account'), ('Current Liabilities', 'Current Liabilities'), ('Reserves And Surplus A/C', 'Reserves And Surplus A/C'), ('Salary Payable', 'Salary Payable'), ('Statutary Liabilities', 'Statutary Liabilities'), ('Other Liabilities', 'Other Liabilities'), ('Branches', 'Branches'), ('Sundry Creditors', 'Sundry Creditors'), ('Secured Loan', 'Secured Loan'), ('Insecured Loan', 'Insecured Loan')], max_length=100, null=True)),
                ('op_balance', models.IntegerField(blank=True, null=True)),
                ('cr_or_dr', models.CharField(blank=True, choices=[('CR', 'CR'), ('DR', 'DR')], max_length=20, null=True)),
                ('has_child_acc', models.BooleanField(default=False)),
                ('unique_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('unique_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
    ]
