# Generated by Django 5.1.5 on 2025-02-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0013_globalcustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_head', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, choices=[('Direct Expenses', 'Direct Expenses'), ('Indirect Expenses', 'Indirect Expenses')], max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('unique_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_head', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, choices=[('Visa Service Incomes', 'Visa Service Incomes'), ('Ticketing Incomes', 'Ticketing Incomes'), ('Attestation Incomes', 'Attestation Incomes'), ('Emigration Income', 'Emigration Income'), ('Umrah Income', 'Umrah Income'), ('Other Incomes', 'Other Incomes'), ('Recruitment Incomes', 'Recruitment Incomes'), ('Insurance Incomes', 'Insurance Incomes'), ('Service Income', 'Service Income')], max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('unique_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalLiability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_head', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, choices=[('Capital Account', 'Capital Account'), ('Current Liabilities', 'Current Liabilities'), ('Reserves And Surplus A/C', 'Reserves And Surplus A/C'), ('Salary Payable', 'Salary Payable'), ('Statutary Liabilities', 'Statutary Liabilities'), ('Other Liabilities', 'Other Liabilities'), ('Branches', 'Branches'), ('Sundry Creditors', 'Sundry Creditors'), ('Secured Loan', 'Secured Loan'), ('Insecured Loan', 'Insecured Loan')], max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('unique_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalNeutral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_head', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, choices=[('Neutral', 'Neutral')], max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('unique_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalSuppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_head', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, choices=[('Supplier', 'Supplier'), ('Airline Supplier', 'Airline Supplier')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('unique_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
    ]
