# Generated by Django 5.1.5 on 2025-02-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0014_globalexpense_globalincome_globalliability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='acc_type',
            field=models.CharField(blank=True, choices=[('Customer', 'Customer')], max_length=20, null=True),
        ),
    ]
