# Generated by Django 5.1.5 on 2025-02-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0015_customer_acc_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neutral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('create_child_acc', models.BooleanField(default=False)),
                ('create_parent_acc', models.BooleanField(default=False)),
                ('choose_parent', models.CharField(blank=True, max_length=255, null=True)),
                ('op_balance', models.IntegerField(blank=True, null=True)),
                ('cr_or_dr', models.CharField(blank=True, choices=[('CR', 'CR'), ('DR', 'DR')], max_length=20, null=True)),
                ('has_credit_limit', models.BooleanField(default=False)),
                ('enter_limit', models.IntegerField(blank=True, null=True)),
                ('contact_details', models.TextField(blank=True, null=True)),
                ('gst_in', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('staff_or_group', models.CharField(blank=True, max_length=255, null=True)),
                ('unique_code', models.CharField(max_length=255, unique=True)),
                ('id_or_pan', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('acl_type', models.CharField(blank=True, choices=[('BC', 'BC'), ('BB', 'BB')], max_length=20, null=True)),
                ('acc_type', models.CharField(blank=True, choices=[('Neutral', 'Neutral')], max_length=20, null=True)),
            ],
        ),
    ]
