# Generated by Django 5.1.5 on 2025-02-07 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0016_neutral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_date', models.DateField(blank=True, null=True)),
                ('ref_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_details', models.TextField(blank=True, null=True)),
                ('pax_details', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, default='INR', max_length=10, null=True)),
                ('total_fare', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='admins.quotation')),
            ],
        ),
    ]
