# Generated by Django 5.1.5 on 2025-02-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0017_quotation_servicedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
