# Generated by Django 5.1.5 on 2025-02-07 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0018_quotation_unique_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='unique_id',
            new_name='quatation_no',
        ),
    ]
