# Generated by Django 5.1.5 on 2025-02-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0020_alter_expenses_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceived',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
